### ISSUE TITLE
Deprecated in favor of what?

### ISSUE THREAD

**Issue by NobbZ** [thestinger/rust-gmp#24]
[Line 3 of src/lib.rs](https://github.com/thestinger/rust-gmp/blob/master/src/lib.rs#L3) tells:

```rs
#![warn(deprecated)]
```

So what to use instead?

To be clear: I'm searching for something to use big integers and/or big fixed point numbers in a project of mine.

**Comment by thestinger** [comment]
This project along with any other Rust projects on my account are no longer maintained. I recommend using a different programming language. That line is just fiddling with a warning setting in the compiler though - it's not telling you that the crate is deprecated.
